"""
Django settings for anipalengke project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import firebase_admin
from firebase_admin import credentials

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-vuq-&t5@hha+jxr!m-fkh%c3hci999i*@fz*fgkc0^89#grj1+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://anipalengke.onrender.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'users',
    'products',
    'orders',
    'community',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.FirebaseUserMiddleware', # Custom Middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'anipalengke.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'anipalengke.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "core/static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Gemini API Key
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Logistics API Key
LOGISTICS_API_KEY = os.getenv('LOGISTICS_API_KEY')

# Payment Gateway Key
PAYMENT_GATEWAY_KEY = os.getenv('PAYMENT_GATEWAY_KEY')

# Firebase Initialization
try:
    if not firebase_admin._apps:
        cred = None
        
        # 1. Check Local File
        local_cred_path = BASE_DIR / 'serviceAccountKey.json'
        
        # 2. Check Render Secret File (Standard Path)
        render_cred_path = Path('/etc/secrets/serviceAccountKey.json')
        
        # 3. Check Environment Variable (JSON Content)
        env_creds = os.getenv('FIREBASE_CREDENTIALS_JSON')

        if local_cred_path.exists():
            cred = credentials.Certificate(str(local_cred_path))
            print(f"Firebase: Loaded from local file: {local_cred_path}")
        elif render_cred_path.exists():
            cred = credentials.Certificate(str(render_cred_path))
            print(f"Firebase: Loaded from Render secret file: {render_cred_path}")
        elif env_creds:
            import json
            cred_dict = json.loads(env_creds)
            cred = credentials.Certificate(cred_dict)
            print("Firebase: Loaded from environment variable")
            
        if cred:
            firebase_admin.initialize_app(cred)
            print("\n---------------------------------------------------")
            print("SUCCESS: Firebase initialized")
            print("---------------------------------------------------\n")
        else:
            print("Warning: No Firebase credentials found (checked local, /etc/secrets, and env var).")
except Exception as e:
    print(f"Error initializing Firebase: {e}")


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.file'

# Email Configuration (Development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Security Settings for Google Sign-In
# This is required to allow the Google Sign-In popup to communicate with the window
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# Lalamove Configuration
LALAMOVE_API_KEY = os.getenv('LALAMOVE_API_KEY', 'pk_test_12345') # Default to a dummy key for dev if not set
LALAMOVE_API_SECRET = os.getenv('LALAMOVE_API_SECRET', 'sk_test_12345')
LALAMOVE_BASE_URL = os.getenv('LALAMOVE_BASE_URL', 'https://rest.sandbox.lalamove.com')
LALAMOVE_MARKET = 'PH'

# PayMongo Configuration
PAYMONGO_PUBLIC_KEY = os.getenv('PAYMONGO_PUBLIC_KEY', 'pk_test_your_public_key')
PAYMONGO_SECRET_KEY = os.getenv('PAYMONGO_SECRET_KEY', 'sk_test_your_secret_key')
PAYMONGO_BASE_URL = os.getenv('PAYMONGO_BASE_URL', 'https://api.paymongo.com/v1')
